name: CI - Unit Tests (Test)
on:
  pull_request:
    branches: [ "test" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Run Unit Tests
        run: npm run test:unit